name: Terraform CI
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  terraform_ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      id: checkout_repo
      uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0

    - name: Terraform setup 
      id: terraform_setup
      uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
      with: 
        terraform_version: "1.6.5"

    - name: Terraform init
      id: terraform_init
      run: terraform init

    - name: Terraform fmt
      id: terraform_fmt
      run: terraform fmt -diff -check

    - name: Terraform validate
      id: terraform_validate
      run: terraform validate